substitutions:
  name: solax-meter-gateway
  device_description: "Control the export of a Solax X1 mini via RS485"
  external_components_source: github://syssi/esphome-modbus-solax-x1@main
  instantaneous_power_topic0: "stat/EZ3/P_Wirk_L1"
  instantaneous_power_topic1: "stat/EZ3/P_Wirk_L2"
  device0: x1-mini-l1
  device1: x1-mini-l2

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-modbus-solax-x1"
    version: 2.2.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

api:
  reboot_timeout: 0s

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3
  - id: uart_1
    baud_rate: 9600
    tx_pin: GPIO14
    rx_pin: GPIO4

solax_meter_modbus:
  - id: modbus0
    uart_id: uart_0
  - id: modbus1
    uart_id: uart_1

solax_meter_gateway:
  - id: solax_meter_gateway0
    solax_meter_modbus_id: modbus0
    address: 0x01

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0
    power_sensor_inactivity_timeout: 5s
    update_interval: 1s

  - id: solax_meter_gateway1
    solax_meter_modbus_id: modbus1
    address: 0x01

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter1
    power_sensor_inactivity_timeout: 5s
    update_interval: 1s

sensor:
  - id: powermeter0
    internal: true
    platform: mqtt_subscribe
    name: "${device0} instantaneous power consumption"
    topic: "${instantaneous_power_topic0}"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power

  - id: powermeter1
    internal: true
    platform: mqtt_subscribe
    name: "${device1} instantaneous power consumption"
    topic: "${instantaneous_power_topic1}"
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power

  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway0
    power_demand:
      name: "${device0} power demand"

  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway1
    power_demand:
      name: "${device1} power demand"

text_sensor:
  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway0
    operation_mode:
      name: "${device0} operation mode"

  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway1
    operation_mode:
      name: "${device1} operation mode"

switch:
  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway0
    emergency_power_off:
      name: "${device0} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

  - platform: solax_meter_gateway
    solax_meter_gateway_id: solax_meter_gateway1
    emergency_power_off:
      name: "${device1} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF
