substitutions:
  name: solar-powermeter
  device_description: "Monitor multiple Solax X1 mini via RS485"
  external_components_source: github://syssi/esphome-solax-x1-mini@main
  device0: firstfloor-solar-powermeter
  device1: groundfloor-solar-powermeter
  device2: community-solar-powermeter

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-solax-x1-mini"
    version: 1.2.1

esp32:
  board: esp-wrover-kit

external_components:
  - source: ${external_components_source}
    refresh: 0s

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

ota:

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

logger:
  baud_rate: 0
  level: DEBUG

uart:
  - id: uart0
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3
  - id: uart1
    baud_rate: 9600
    tx_pin: GPIO14
    rx_pin: GPIO4
  - id: uart2
    baud_rate: 9600
    tx_pin: GPIO32
    rx_pin: GPIO33

solax_modbus:
  - id: modbus0
    uart_id: uart0
  - id: modbus1
    uart_id: uart1
  - id: modbus2
    uart_id: uart2

solax_x1_mini:
  - id: solax0
    solax_modbus_id: modbus0
    update_interval: 2s
  - id: solax1
    solax_modbus_id: modbus1
    update_interval: 2s
  - id: solax2
    solax_modbus_id: modbus2
    update_interval: 2s

text_sensor:
  - platform: solax_x1_mini
    solax_x1_mini_id: solax0
    mode_name:
      name: "${device0} mode name"
    errors:
      name: "${device0} errors"

  - platform: solax_x1_mini
    solax_x1_mini_id: solax1
    mode_name:
      name: "${device1} mode name"
    errors:
      name: "${device1} errors"

  - platform: solax_x1_mini
    solax_x1_mini_id: solax2
    mode_name:
      name: "${device2} mode name"
    errors:
      name: "${device2} errors"

sensor:
  - platform: solax_x1_mini
    solax_x1_mini_id: solax0
    ac_power:
      name: "${device0} ac power"
    energy_today:
      name: "${device0} energy today"
    energy_total:
      name: "${device0} energy total"
    dc1_voltage:
      name: "${device0} dc1 voltage"
    dc1_current:
      name: "${device0} dc1 current"
    ac_current:
      name: "${device0} ac current"
    ac_voltage:
      name: "${device0} ac voltage"
    ac_frequency:
      name: "${device0} ac frequency"
    temperature:
      name: "${device0} temperature"
    runtime_total:
      name: "${device0} runtime total"
    mode:
      name: "${device0} mode"
    error_bits:
      name: "${device0} error bits"
    grid_voltage_fault:
      name: "${device0} grid voltage fault"
    grid_frequency_fault:
      name: "${device0} grid frequency fault"
    dc_injection_fault:
      name: "${device0} dc injection fault"
    temperature_fault:
      name: "${device0} temperature fault"
    pv1_voltage_fault:
      name: "${device0} pv1 voltage fault"
    pv2_voltage_fault:
      name: "${device0} pv2 voltage fault"
    gfc_fault:
      name: "${device0} gfc fault"

  - platform: solax_x1_mini
    solax_x1_mini_id: solax1
    ac_power:
      name: "${device1} ac power"
    energy_today:
      name: "${device1} energy today"
    energy_total:
      name: "${device1} energy total"
    dc1_voltage:
      name: "${device1} dc1 voltage"
    dc1_current:
      name: "${device1} dc1 current"
    ac_current:
      name: "${device1} ac current"
    ac_voltage:
      name: "${device1} ac voltage"
    ac_frequency:
      name: "${device1} ac frequency"
    temperature:
      name: "${device1} temperature"
    runtime_total:
      name: "${device1} runtime total"
    mode:
      name: "${device1} mode"
    error_bits:
      name: "${device1} error bits"
    grid_voltage_fault:
      name: "${device1} grid voltage fault"
    grid_frequency_fault:
      name: "${device1} grid frequency fault"
    dc_injection_fault:
      name: "${device1} dc injection fault"
    temperature_fault:
      name: "${device1} temperature fault"
    pv1_voltage_fault:
      name: "${device1} pv1 voltage fault"
    pv2_voltage_fault:
      name: "${device1} pv2 voltage fault"
    gfc_fault:
      name: "${device1} gfc fault"

  - platform: solax_x1_mini
    solax_x1_mini_id: solax2
    ac_power:
      name: "${device2} ac power"
    energy_today:
      name: "${device2} energy today"
    energy_total:
      name: "${device2} energy total"
    dc1_voltage:
      name: "${device2} dc1 voltage"
    dc1_current:
      name: "${device2} dc1 current"
    ac_current:
      name: "${device2} ac current"
    ac_voltage:
      name: "${device2} ac voltage"
    ac_frequency:
      name: "${device2} ac frequency"
    temperature:
      name: "${device2} temperature"
    runtime_total:
      name: "${device2} runtime total"
    mode:
      name: "${device2} mode"
    error_bits:
      name: "${device2} error bits"
    grid_voltage_fault:
      name: "${device2} grid voltage fault"
    grid_frequency_fault:
      name: "${device2} grid frequency fault"
    dc_injection_fault:
      name: "${device2} dc injection fault"
    temperature_fault:
      name: "${device2} temperature fault"
    pv1_voltage_fault:
      name: "${device2} pv1 voltage fault"
    pv2_voltage_fault:
      name: "${device2} pv2 voltage fault"
    gfc_fault:
      name: "${device2} gfc fault"
