substitutions:
  name: solax-x1-mini
  device_description: "Monitor a Solax X1 mini via RS485"
  external_components_source: github://syssi/esphome-solax-x1-mini@main
  tx_pin: GPIO16
  rx_pin: GPIO17

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-solax-x1-mini"
    version: 2.1.0

esp32:
  board: wemos_d1_mini32

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  id: uart_0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

solax_modbus:
  - id: modbus0
    uart_id: uart_0
#    flow_control_pin: GPIO0

solax_x1_mini:
  solax_modbus_id: modbus0
  update_interval: 1s

text_sensor:
  - platform: solax_x1_mini
    mode_name:
      name: "${name} mode name"
    errors:
      name: "${name} errors"

sensor:
  - platform: solax_x1_mini
    ac_power:
      name: "${name} ac power"
    energy_today:
      name: "${name} energy today"
    energy_total:
      name: "${name} energy total"
    dc1_voltage:
      name: "${name} dc1 voltage"
    dc2_voltage:
      name: "${name} dc2 voltage"
    dc1_current:
      name: "${name} dc1 current"
    dc2_current:
      name: "${name} dc2 current"
    ac_current:
      name: "${name} ac current"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"
    runtime_total:
      name: "${name} runtime total"
    mode:
      name: "${name} mode"
    error_bits:
      name: "${name} error bits"
    grid_voltage_fault:
      name: "${name} grid voltage fault"
    grid_frequency_fault:
      name: "${name} grid frequency fault"
    dc_injection_fault:
      name: "${name} dc injection fault"
    temperature_fault:
      name: "${name} temperature fault"
    pv1_voltage_fault:
      name: "${name} pv1 voltage fault"
    pv2_voltage_fault:
      name: "${name} pv2 voltage fault"
    gfc_fault:
      name: "${name} gfc fault"
