substitutions:
  name: solax-x1-mini
  device_description: "Monitor multiple Solax X1 mini via RS485"
  external_components_source: github://syssi/esphome-solax-x1-mini@main
  device0: firstfloor-x1-mini
  device1: groundfloor-x1-mini
  device2: community-x1-mini

esphome:
  name: ${name}
  friendly_name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-solax-x1-mini"
    version: 2.6.0
  devices:
    - id: device0
      name: "${device0}"
    - id: device1
      name: "${device1}"
    - id: device2
      name: "${device2}"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

ota:
  platform: esphome

logger:
  baud_rate: 0
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3
  - id: uart_1
    baud_rate: 9600
    tx_pin: GPIO14
    rx_pin: GPIO4
  - id: uart_2
    baud_rate: 9600
    tx_pin: GPIO32
    rx_pin: GPIO33

solax_modbus:
  - id: modbus0
    uart_id: uart_0
  - id: modbus1
    uart_id: uart_1
  - id: modbus2
    uart_id: uart_2

solax_x1_mini:
  - id: solax0
    solax_modbus_id: modbus0
    update_interval: 2s
  - id: solax1
    solax_modbus_id: modbus1
    update_interval: 2s
  - id: solax2
    solax_modbus_id: modbus2
    update_interval: 2s

text_sensor:
  - platform: solax_x1_mini
    solax_x1_mini_id: solax0
    mode_name:
      name: "${device0} mode name"
      device_id: device0
    errors:
      name: "${device0} errors"
      device_id: device0

  - platform: solax_x1_mini
    solax_x1_mini_id: solax1
    mode_name:
      name: "${device1} mode name"
      device_id: device1
    errors:
      name: "${device1} errors"
      device_id: device1

  - platform: solax_x1_mini
    solax_x1_mini_id: solax2
    mode_name:
      name: "${device2} mode name"
      device_id: device2
    errors:
      name: "${device2} errors"
      device_id: device2

sensor:
  - platform: solax_x1_mini
    solax_x1_mini_id: solax0
    ac_power:
      name: "${device0} ac power"
      device_id: device0
    energy_today:
      name: "${device0} energy today"
      device_id: device0
    energy_total:
      name: "${device0} energy total"
      device_id: device0
    dc1_voltage:
      name: "${device0} dc1 voltage"
      device_id: device0
    dc1_current:
      name: "${device0} dc1 current"
      device_id: device0
    ac_current:
      name: "${device0} ac current"
      device_id: device0
    ac_voltage:
      name: "${device0} ac voltage"
      device_id: device0
    ac_frequency:
      name: "${device0} ac frequency"
      device_id: device0
    temperature:
      name: "${device0} temperature"
      device_id: device0
    runtime_total:
      name: "${device0} runtime total"
      device_id: device0
    mode:
      name: "${device0} mode"
      device_id: device0
    error_bits:
      name: "${device0} error bits"
      device_id: device0
    grid_voltage_fault:
      name: "${device0} grid voltage fault"
      device_id: device0
    grid_frequency_fault:
      name: "${device0} grid frequency fault"
      device_id: device0
    dc_injection_fault:
      name: "${device0} dc injection fault"
      device_id: device0
    temperature_fault:
      name: "${device0} temperature fault"
      device_id: device0
    pv1_voltage_fault:
      name: "${device0} pv1 voltage fault"
      device_id: device0
    pv2_voltage_fault:
      name: "${device0} pv2 voltage fault"
      device_id: device0
    gfc_fault:
      name: "${device0} gfc fault"
      device_id: device0

  - platform: solax_x1_mini
    solax_x1_mini_id: solax1
    ac_power:
      name: "${device1} ac power"
      device_id: device1
    energy_today:
      name: "${device1} energy today"
      device_id: device1
    energy_total:
      name: "${device1} energy total"
      device_id: device1
    dc1_voltage:
      name: "${device1} dc1 voltage"
      device_id: device1
    dc1_current:
      name: "${device1} dc1 current"
      device_id: device1
    ac_current:
      name: "${device1} ac current"
      device_id: device1
    ac_voltage:
      name: "${device1} ac voltage"
      device_id: device1
    ac_frequency:
      name: "${device1} ac frequency"
      device_id: device1
    temperature:
      name: "${device1} temperature"
      device_id: device1
    runtime_total:
      name: "${device1} runtime total"
      device_id: device1
    mode:
      name: "${device1} mode"
      device_id: device1
    error_bits:
      name: "${device1} error bits"
      device_id: device1
    grid_voltage_fault:
      name: "${device1} grid voltage fault"
      device_id: device1
    grid_frequency_fault:
      name: "${device1} grid frequency fault"
      device_id: device1
    dc_injection_fault:
      name: "${device1} dc injection fault"
      device_id: device1
    temperature_fault:
      name: "${device1} temperature fault"
      device_id: device1
    pv1_voltage_fault:
      name: "${device1} pv1 voltage fault"
      device_id: device1
    pv2_voltage_fault:
      name: "${device1} pv2 voltage fault"
      device_id: device1
    gfc_fault:
      name: "${device1} gfc fault"
      device_id: device1

  - platform: solax_x1_mini
    solax_x1_mini_id: solax2
    ac_power:
      name: "${device2} ac power"
      device_id: device2
    energy_today:
      name: "${device2} energy today"
      device_id: device2
    energy_total:
      name: "${device2} energy total"
      device_id: device2
    dc1_voltage:
      name: "${device2} dc1 voltage"
      device_id: device2
    dc1_current:
      name: "${device2} dc1 current"
      device_id: device2
    ac_current:
      name: "${device2} ac current"
      device_id: device2
    ac_voltage:
      name: "${device2} ac voltage"
      device_id: device2
    ac_frequency:
      name: "${device2} ac frequency"
      device_id: device2
    temperature:
      name: "${device2} temperature"
      device_id: device2
    runtime_total:
      name: "${device2} runtime total"
      device_id: device2
    mode:
      name: "${device2} mode"
      device_id: device2
    error_bits:
      name: "${device2} error bits"
      device_id: device2
    grid_voltage_fault:
      name: "${device2} grid voltage fault"
      device_id: device2
    grid_frequency_fault:
      name: "${device2} grid frequency fault"
      device_id: device2
    dc_injection_fault:
      name: "${device2} dc injection fault"
      device_id: device2
    temperature_fault:
      name: "${device2} temperature fault"
      device_id: device2
    pv1_voltage_fault:
      name: "${device2} pv1 voltage fault"
      device_id: device2
    pv2_voltage_fault:
      name: "${device2} pv2 voltage fault"
      device_id: device2
    gfc_fault:
      name: "${device2} gfc fault"
      device_id: device2
