substitutions:
  name: solar-powermeter
  device_description: "Monitor a Solax X1 mini via RS485"
  external_components_source: github://syssi/esphome-modbus-solax-x1@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-modbus-solax-x1"
    version: 1.2.1

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

logger:
  level: DEBUG

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}

modbus_solax:
  - id: modbus0
    uart_id: uart0
#    flow_control_pin: GPIO0

solax_x1:
  modbus_solax_id: modbus0
  update_interval: 1s

text_sensor:
  - platform: solax_x1
    mode_name:
      name: "${name} mode name"
    errors:
      name: "${name} errors"

sensor:
  - platform: solax_x1
    ac_power:
      name: "${name} ac power"
    energy_today:
      name: "${name} energy today"
    energy_total:
      name: "${name} energy total"
    dc1_voltage:
      name: "${name} dc1 voltage"
    dc2_voltage:
      name: "${name} dc2 voltage"
    dc1_current:
      name: "${name} dc1 current"
    dc2_current:
      name: "${name} dc2 current"
    ac_current:
      name: "${name} ac current"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"
    runtime_total:
      name: "${name} runtime total"
    mode:
      name: "${name} mode"
    error_bits:
      name: "${name} error bits"
    grid_voltage_fault:
      name: "${name} grid voltage fault"
    grid_frequency_fault:
      name: "${name} grid frequency fault"
    dc_injection_fault:
      name: "${name} dc injection fault"
    temperature_fault:
      name: "${name} temperature fault"
    pv1_voltage_fault:
      name: "${name} pv1 voltage fault"
    pv2_voltage_fault:
      name: "${name} pv2 voltage fault"
    gfc_fault:
      name: "${name} gfc fault"
